spring:
  application:
    name: catdfs

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 8080

catdfs:
  path: D:\test\catdfs
  backupUrl: http://localhost:8081/sync
  autoMd5: true
